#!/bin/bash

books() {
    n1=$(ls $HOME/workspace/books | fzf)
    cd $HOME/workspace/books
    [[ -n $n1 ]] && zathura "$n1" 2>/dev/null &
}

main() {
    case $1 in
        'b')
            books;return ;;
    esac

    func=$(echo -e "books\nmusics" | fzf)
    case $func in
        'books')
            books;;
    esac
}

main $@
