#!/bin/sh

s1=("aria2" "fontconfig" "mpd" "newsboat" "qrcp" "tmux" "zathura" "dunst" "lazygit" "mpv" "nvim" "redshift" "btop" "emacs" "git" "lf" "ncmpcpp" "picom" "rofi" "yt-dlp")
s2=("Xmodmap" "inputrc" "xinitrc")

for item in ${s1[*]}
do
  echo "====================================================="
  ls $HOME/.config/$item > /dev/null 2>&1 && rm -rv $HOME/.config/$item
  ln -sfv $HOME/workspace/Dotfiles/$item $HOME/.config/$item
  echo -e "=====================================================\n"
done

for item in ${s2[*]}
do
  echo "====================================================="
  ls $HOME/.$item > /dev/null 2>&1 && rm -rv $HOME/.$item
  ln -sfv $HOME/workspace/Dotfiles/$1 $HOME/.$item
  echo -e "=====================================================\n"
done
