#!/bin/sh

_thisdir=$(cd $(dirname $0); pwd)
echo "omb=$_thisdir" > $HOME/.bashrc
echo 'source $omb/rc' >> $HOME/.bashrc
mkdir -P $HOME/.local/bin && ln -svf $_thisdir/scripts/lfub $HOME/.local/bin/lfub
