#!/bin/sh

source $omb/config/envs.sh
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
source $omb/config/settings.sh
source $omb/config/prompt.sh
source $omb/config/aliases.sh
source $omb/config/fzf.sh
