#!/usr/bin/env bash

_thisdir=$(cd $(dirname $0); pwd)

ohmyposh() {
	local url='https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64'
	aria2c --out="posh-linux-amd64" $url || return
	cp -v $_thisdir/posh-linux-amd64 $_thisdir/plugins/ohmyposh/oh-my-posh
	chmod u+x $_thisdir/plugins/ohmyposh/oh-my-posh
	rm -v $_thisdir/posh-linux-amd64
    echo -e "Finished.\n"
}

zlua() {
	local url='https://raw.githubusercontent.com/skywind3000/z.lua/master/z.lua'
	aria2c --out="z.lua" $url || return
	cp -v $_thisdir/z.lua $_thisdir/plugins/z/z.lua
	rm -v $_thisdir/z.lua
    echo -e "Finished.\n"
}

ohmyposh
zlua
